const items = [
  "Anklet",
  "Armlet",
  "Backpack",
  "Bandana",
  "Belt",
  "Beret",
  "Bolo tie",
  "Bonnet",
  "Bowtie",
  "Bracelet",
  "Brooch",
  "Cane",
  "Cardigan",
  "Choker",
  "Clutch",
  "Collar pin",
  "Crown",
  "Cufflinks",
  "Cummerbund",
  "Diadem",
  "Duffle bag",
  "Durag",
  "Ear cuffs",
  "Earmuffs",
  "Earrings",
  "Eyeglasses",
  // amazonq-ignore-next-line
  // amazonq-ignore-next-line
  "Fanny pack",
  "Fascinator",
  "Fedora",
  "Fingerless gloves",
  "Fishnet stockings",
  "Gaiters",
  "Glasses",
  "Gloves",
  "Hairpin",
  "Handbag",
  "Handkerchief",
  "Hat",
  "Headband",
  "Insoles",
  "Jewelry",
  "Keychain",
  "Kippah",
  "Lapel pin",
  "Leg warmers",
  "Mittens",
  "Muff",
  "Necklace",
  "Nose ring",
  "Over-the-knee socks",
  "Panama hat",
  "Parasol",
  "Pendant",
  "Pocket square",
  "Pocket watch",
  "Purse",
  "Quartz watch",
  "Quilted handbag",
  "Ring",
  "Sash",
  "Scarf",
  "Shawl",
  "Sunglasses",
  "Suspenders",
  "Tiara",
  "Tie",
  "Tights",
  "Toe rings",
  "Umbrella",
  "Veil",
  "Vest",
  "Visor",
  "Waistcoat",
  "Wallet chain",
  "Watch",
  "Wristlet",
  "Yarmulke",
  "Zirconia earrings"
]
export default items;