const items = [
  "Acrylic adhesive",
  "Animal glue",
  "Barge cement",
  "Bookbinding glue",
  "Carpenter's glue",
  "Caulk",
  "Cement glue",
  "Contact cement",
  "Craft glue",
  "Cyanoacrylate",
  "Double-sided tape",
  "Duct tape",
  "Electrical tape",
  "Epoxy",
  "Fabric glue",
  "Foam tape",
  "Gaffer tape",
  "Gorilla glue",
  "Hide glue",
  "Hot glue",
  "Instant adhesive",
  "Latex adhesive",
  "Liquid nails",
  "Masking tape",
  "Metal epoxy",
  "Mounting tape",
  "Mucilage",
  "Neoprene adhesive",
  "Paper glue",
  "Paste",
  "PVA glue",
  "Resin adhesive",
  "Rubber cement",
  "Sealant",
  "Silicone adhesive",
  "Spray adhesive",
  "Starch paste",
  "Sticky tack",
  "Super glue",
  "Tape",
  "Thermoplastic adhesive",
  "Tile adhesive",
  "Transparent tape",
  "Two-part epoxy",
  "Vinyl adhesive",
  "Waterproof glue",
  "Washi tape",
  "Welding adhesive",
  "Wood glue"
]
export default items;