const items = [
  "Amulet of protection",
  "Ancient grimoire",
  "Arcane crystal",
  "Astral compass",
  "Bag of holding",
  "Bewitched mirror",
  "Blessed chalice",
  "Bottled fairy",
  "Celestial map",
  "Charmed locket",
  "Crystal ball",
  "Cursed dagger",
  "Dragon scale",
  "Dreamcatcher",
  "Elemental orb",
  "Enchanted armor",
  "Enchanted quill",
  "Ethereal dust",
  "Fairy dust",
  "Flying carpet",
  "Fortune telling cards",
  "Genie lamp",
  "Ghost lantern",
  "Glowing mushroom",
  "Goblin trinket",
  "Golden compass",
  "Healing potion",
  "Invisibility cloak",
  "Levitation boots",
  "Lich's phylactery",
  "Lucky coin",
  "Magic beans",
  "Magic wand",
  "Mana crystal",
  "Mermaid's tear",
  "Moonstone",
  "Mystic hourglass",
  "Necromancer's staff",
  "Oracle bones",
  "Phoenix feather",
  "Potion of flight",
  "Resurrection stone",
  "Rune stone",
  "Scrying bowl",
  "Seer's crystal",
  "Shrunken head",
  "Siren's shell",
  "Soul gem",
  "Spell book",
  "Spirit bottle",
  "Staff of power",
  "Talisman",
  "Teleportation scroll",
  "Time turner",
  "Unicorn horn",
  "Vial of dragon blood",
  "Voodoo doll",
  "Warlock's pendant",
  "Witch's broom",
  "Wizard hat",
  "Wizard's staff"
]
export default items;