const items = [
  // Cutting Tools
  "adze",
  "angle grinder",
  "axe",
  "bolt cutter",
  "cable cutter",
  "chainsaw",
  "chisel",
  "circular saw",
  "clippers",
  "coping saw",
  "cutters",
  "glass cutter",
  "grinder",
  "hacksaw",
  "handsaw",
  "jigsaw",
  "knife",
  "machete",
  "pipe cutter",
  "pruning shears",
  "razor",
  "reciprocating saw",
  "saw",
  "scalpel",
  "scissors",
  "sheet metal shears",
  "sickle",
  "snips",
  "tin snips",
  "utility knife",
  "wire cutter",
  "band saw",
  "cable saw",
  "circular saw blade",
  "diamond blade",
  "glass breaker",
  "glass saw",
  "hacksaw blade",
  "hole punch",
  "jigsaw blade",
  "keyhole saw",
  "masonry saw",
  "metal cutting saw",
  "pipe saw",
  "reciprocating saw blade",
  "rotary saw",
  "saw blade",
  "scoring knife",
  "tile cutter",
  "wire saw",
  "wood splitter",
  "bolt cropper",
  "cable stripper",
  "diamond saw",
  "drywall saw",
  "fiberglass cutter",
  "foam cutter",
  "hole saw",
  "kerfing saw",
  "miter saw",
  "oscillating tool",
  "panel saw",
  "plunge saw",
  "pole saw",
  "radial arm saw",
  "scroll saw",
  "table saw",
  "track saw",
  "undercut saw",
  "veneer saw",

  // Measuring and Layout Tools
  "calipers",
  "chalk line",
  "feeler gauge",
  "laser level",
  "level",
  "measuring tape",
  "plumb bob",
  "ruler",
  "square",
  "stud finder",
  "yard stick",
  "combination square",
  "framing square",
  "speed square",
  "thread gauge",

  // Fastening Tools
  "Allen wrench",
  "bolt",
  "brad",
  "hex wrench",
  "nail",
  "nut",
  "pin",
  "rivet",
  "screw",
  "screwdriver",
  "spanner",
  "staple",
  "tack",
  "wrench",
  "monkey wrench",
  "Phillips screwdriver",
  "lug wrench",
  "anchor bolt",
  "binding post",
  "carriage bolt",
  "clamp screw",
  "coach screw",
  "concrete screw",
  "deck screw",
  "drywall screw",
  "eye bolt",
  "flat head screw",
  "hanger bolt",
  "hex bolt",
  "lag bolt",
  "machine screw",
  "pan head screw",
  "security screw",
  "self-tapping screw",
  "set screw",
  "socket head screw",
  "thumb screw",
  "toggle bolt",
  "wing nut",
  "wing screw",
  "wood screw",
  "zip tie",
  "cable tie",
  "hog ring",
  "hog ring pliers",
  "rivet nut",
  "snap rivet",
  "split rivet",
  "threaded insert",
  "threaded rod",
  "U-bolt",
  "wire rope clip",

  // Power Tools
  "air compressor",
  "arc welder",
  "brad nailer",
  "die grinder",
  "drill",
  "drill press",
  "electric drill",
  "flux core welder",
  "impact driver",
  "impact wrench",
  "mig welder",
  "nail gun",
  "paint sprayer",
  "plasma cutter",
  "power drill",
  "pressure washer",
  "rivet gun",
  "router",
  "sander",
  "soldering iron",
  "spot welder",
  "torch",
  "oxy-acetylene torch",

  // Gripping and Holding Tools
  "bench vise",
  "clamp",
  "locking pliers",
  "needle-nose pliers",
  "pincer",
  "pliers",
  "snap ring pliers",
  "toggle clamp",
  "tongs",
  "vise",

  // Electrical Tools
  "battery tester",
  "circuit tester",
  "digital multimeter",
  "electrical tape",
  "voltage tester",
  "fish tape",

  // Joining and Adhesive Tools
  "glue",
  "glue gun",
  "welding helmet",
  "duct tape",
  "epoxy",
  "hot glue",
  "liquid nails",
  "super glue",
  "wood glue",

  // Finishing and Surface Tools
  "brush",
  "file set",
  "metal file",
  "putty knife",
  "rasp",
  "roller",
  "sand paper",
  "scraper",
  "sponge",
  "squeegee",
  "wire brush",
  "wood rasp",

  // Lifting and Moving Tools
  "block and tackle",
  "chain hoist",
  "engine hoist",
  "hydraulic jack",
  "lever",
  "pulley",
  "ratchet strap",
  "rope",

  // Specialized Tools
  "anvil",
  "bevel",
  "blowtorch",
  "countersink",
  "crimping tool",
  "crowbar",
  "deburring tool",
  "edger",
  "extension cord",
  "flaring tool",
  "grease gun",
  "heat gun",
  "jig",
  "lathe",
  "magnetic pickup tool",
  "mallet",
  "metal detector",
  "miter box",
  "pitchfork",
  "portable generator",
  "pry bar",
  "reamer",
  "sharpener",
  "shovel",
  "sledgehammer",
  "socket set",
  "spade",
  "spear",
  "tiller",
  "tire iron",
  "toolbox",
  "torque wrench",
  "trowel",
  "vacuum pump",
  "wedge",
  "workbench",
  "bolt extractor",
  "center punch",
  "dremel",
  "hand seamer",
  "hole saw",
  "laser thermometer",
  "multitool",
  "nibbler",
  "pipe threader",
  "plumb line",
  "rotary tool",
  "tap wrench",
  "tube cutter",
  "wood chisel"
]
export default items;