const items = [
  "adze",
  "air compressor",
  "Allen wrench",
  "angle grinder",
  "anvil",
  "arc welder",
  "axe",
  "battery tester",
  "bellows",
  "bench vise",
  "bevel",
  "blowtorch",
  "block and tackle",
  "block plane",
  "bolt",
  "bolt cutter",
  "brad",
  "brad nailer",
  "brush",
  "cable cutter",
  "calipers",
  "carpenter",
  "chain hoist",
  "chainsaw",
  "chalk line",
  "chisel",
  "circuit tester",
  "circular saw",
  "clamp",
  "clippers",
  "coping saw",
  "countersink",
  "crimping tool",
  "crowbar",
  "cutters",
  "deburring tool",
  "die grinder",
  "digital multimeter",
  "drill",
  "drill bit",
  "drill press",
  "edger",
  "electric drill",
  "electrical tape",
  "engine hoist",
  "extension cord",
  "fastener",
  "feeler gauge",
  "file set",
  "flaring tool",
  "flux core welder",
  "glass cutter",
  "glue",
  "glue gun",
  "grease gun",
  "grinder",
  "hacksaw",
  "hammer",
  "handsaw",
  "heat gun",
  "hex wrench",
  "hoe",
  "hone",
  "hydraulic jack",
  "impact driver",
  "impact wrench",
  "jig",
  "jigsaw",
  "knife",
  "ladder",
  "laser level",
  "lathe",
  "level",
  "lever",
  "locking pliers",
  "machete",
  "magnetic pickup tool",
  "mallet",
  "measuring tape",
  "metal detector",
  "metal file",
  "mig welder",
  "miter box",
  "monkey wrench",
  "nail",
  "nail gun",
  "nail set",
  "needle-nose pliers",
  "nut",
  "oxy-acetylene torch",
  "paint sprayer",
  "Phillips screwdriver",
  "pickaxe",
  "pin",
  "pincer",
  "pinch",
  "pipe bender",
  "pipe cutter",
  "pipe wrench",
  "pitchfork",
  "plane",
  "plasma cutter",
  "pliers",
  "plow",
  "plumb bob",
  "pneumatic hammer",
  "poker",
  "portable generator",
  "power drill",
  "pressure washer",
  "pruning shears",
  "pry bar",
  "pulley",
  "putty knife",
  "rasp",
  "ratchet",
  "ratchet strap",
  "razor",
  "reamer",
  "reciprocating saw",
  "rivet",
  "rivet gun",
  "roller",
  "rope",
  "router",
  "ruler",
  "safety glasses",
  "sand paper",
  "sander",
  "saw",
  "sawhorse",
  "scalpel",
  "scissors",
  "scraper",
  "screw",
  "screwdriver",
  "scythe",
  "sharpener",
  "sheet metal shears",
  "shovel",
  "sickle",
  "sledgehammer",
  "snap ring pliers",
  "snips",
  "socket set",
  "soldering iron",
  "spade",
  "spanner",
  "spear",
  "sponge",
  "spot welder",
  "square",
  "squeegee",
  "staple",
  "stapler",
  "stud finder",
  "tack",
  "tap and die set",
  "tiller",
  "tin snips",
  "tire iron",
  "toggle clamp",
  "tongs",
  "toolbox",
  "toolmaker",
  "torch",
  "torque wrench",
  "trowel",
  "utility knife",
  "vacuum pump",
  "vise",
  "voltage tester",
  "wedge",
  "welding helmet",
  "wheel",
  "wire brush",
  "wire crimper",
  "wire stripper",
  "woodworker",
  "workbench",
  "wrench",
  "yard stick",
  "duct tape",
  "bolt extractor",
  "center punch",
  "combination square",
  "dremel",
  "fish tape",
  "framing square",
  "hand seamer",
  "hole saw",
  "laser thermometer",
  "lug wrench",
  "multitool",
  "nibbler",
  "pipe threader",
  "plumb line",
  "rotary tool",
  "speed square",
  "tap wrench",
  "thread gauge",
  "tube cutter",
  "wood chisel",
  "wood rasp"
]
export default items;