const items = [
  "action figure",
  "ball",
  "blocks",
  "board game",
  "doll",
  "puzzle",
  "teddy bear",
  "video game",
  "yo-yo",
  "arts and crafts",
  "baby doll",
  "badminton set",
  "baseball",
  "basketball",
  "bath toys",
  "bike",
  "building blocks",
  "chalk",
  "checkers",
  "chess set",
  "climbing toy",
  "coloring books",
  "construction toys",
  "crayons",
  "croquet set",
  "darts",
  "dice",
  "doll house",
  "dominoes",
  "dress-up clothes",
  "educational toys",
  "fidget toys",
  "finger paints",
  "football",
  "frisbee",
  "game console",
  "hopscotch",
  "hula hoop",
  "jigsaw puzzle",
  "jump rope",
  "kite",
  "lego",
  "magic kit",
  "marbles",
  "modeling clay",
  "musical instruments",
  "nerf guns",
  "painting set",
  "play dough",
  "play tent",
  "playing cards",
  "plush toy",
  "pool table",
  "pretend play toys",
  "puppets",
  "puzzle",
  "racket sports",
  "radio control toys",
  "remote control car",
  "ride-on toys",
  "rocking horse",
  "roller blades",
  "roller skates",
  "sand box",
  "scooter",
  "slinky",
  "soccer ball",
  "spinning top",
  "stuffed animals",
  "swing set",
  "tea set",
  "train set",
  "tricycle",
  "video game console",
  "walkie talkies",
  "water toys",
  "xylophone"
];

export default items;
