AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket for storing and serving item images in the AI Scrapyard game. This bucket is used to store all item images that players can find and collect in the game.

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref ImagesLoggingBucket
        LogFilePrefix: images-access-logs/

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 
              - s3:PutObject
            Resource: !Sub "${ImagesBucket.Arn}/*"
            Condition:
              StringEquals:
                'AWS:SourceAccount': !Ref AWS::AccountId
              Bool:
                aws:SecureTransport: "true"

  ImagesLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ImagesLoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesLoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 
              - s3:PutObject
            Resource: !Sub "${ImagesLoggingBucket.Arn}/*"
            Condition:
              StringEquals:
                'AWS:SourceAccount': !Ref AWS::AccountId
              Bool:
                aws:SecureTransport: "true"

Outputs:
  ImagesBucketName:
    Description: Name of the images S3 bucket
    Value: !Ref ImagesBucket
    Export:
      Name: !Sub "${AWS::StackName}-ImagesBucketName"
  ImagesBucketArn:
    Description: ARN of the images S3 bucket
    Value: !GetAtt ImagesBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ImagesBucketArn"
  ImagesLoggingBucketName:
    Description: Name of the images logging S3 bucket
    Value: !Ref ImagesLoggingBucket
    Export:
      Name: !Sub "${AWS::StackName}-ImagesLoggingBucketName"
  PlaceholderOutput:
    Description: Placeholder output value
    Value: "placeholder-s3-bucket-value"
  
